/**
 * Structural guard for plan.topRecommendation's debt-payoff dollar figure.
 *
 * Root cause (confirmed live, 2026-07-27): topRecommendation is generated by
 * planPrompt — an older AI call that predates the Coaching Layer and was
 * never wired into it. Its only protection was a soft instruction ("if you
 * reference debt payoff, use the exact numbers given"). Across two real
 * regenerate-plan runs for the same household/month/credit line (whose own
 * required payment is a fixed computedDebtPayoff.monthlyPayment), the model
 * stated two different dollar amounts for it. A stronger-worded instruction
 * is not a fix — the number must be code-owned, not AI-authored, the same
 * discipline goals/debtPayoff/coaching already use elsewhere in this route.
 *
 * Mechanism: planPrompt requires the model to write the literal placeholder
 * DEBT_PAYMENT_PLACEHOLDER wherever the debt's own monthly payment amount
 * would go, never digits. This alone doesn't structurally stop a model from
 * ignoring the instruction and typing its own number anyway — so
 * enforceDebtFigureInTopRecommendation is the actual gate: the placeholder
 * (if present) is substituted with the real figure first, and THEN the full
 * resulting text — every branch, always — is scanned for any remaining
 * dollar figure that doesn't match the real payment amount. If one is found
 * (whether the model skipped the placeholder entirely, or used it correctly
 * and padded the sentence with an extra invented figure alongside it — the
 * confirmed live blind spot, 2026-07-28: "pay {{DEBT_PAYMENT}}/month plus
 * $833/month to clear it sooner" substituted correctly but let the extra
 * $833 ship untouched), the entire recommendation is discarded and replaced
 * with a deterministic, code-built sentence using the real payment amount.
 * One detection path, used uniformly — never two regexes to keep in sync.
 */

import { escapeRegExp } from './textMatchHelpers';

export const DEBT_PAYMENT_PLACEHOLDER = '{{DEBT_PAYMENT}}';

// Matches both English ($3,000 / $833.33) and French-Canadian (3000$ / 3 000,00 $)
// currency conventions, globally — a fabricated figure must not slip past
// detection just because the model wrote it in French formatting, and every
// occurrence must be checked, not just the first.
const DOLLAR_AMOUNT_RE = /\$\s?[\d,]+(?:[.,]\d{1,2})?|[\d][\d,\s]*(?:[.,]\d{1,2})?\s?\$/g;

// Any {{...}} shaped token, by NAME-AGNOSTIC pattern — not just
// DEBT_PAYMENT_PLACEHOLDER specifically. Confirmed live (2026-07-28): with
// no debt account at all (computedDebtPayoff null), the model still wrote
// the literal "{{DEBT_PAYMENT}}" token in topRecommendation, and the old
// early-return (`if (!debtPayoff) return text`) shipped it untouched — a
// template token has no legitimate reason to ever reach a user. Matching by
// shape, not by the one name we happen to define today, means a future
// prompt template gaining a new placeholder can't silently reopen this same
// hole under a different name. Non-global (no risk from reused .test()
// statefulness) — this is a pure presence check, not a per-occurrence scan.
const TEMPLATE_TOKEN_RE = /\{\{[^{}]*\}\}/;

export function containsUnsubstitutedToken(text: string): boolean {
  return TEMPLATE_TOKEN_RE.test(text);
}

export type DebtPayoffForRecommendation = {
  description: string;
  targetDate: string; // YYYY-MM
  monthlyPayment: number;
};

function formatCurrency(n: number): string {
  return `$${n.toFixed(2)}`;
}

/**
 * Parses a matched currency string (either "$1,234.56" or "1 234,56$") into
 * a plain number. A comma immediately followed by exactly 2 trailing digits
 * is treated as a French decimal separator; otherwise commas/spaces are
 * treated as thousands separators and stripped.
 */
function parseAmount(raw: string): number {
  const stripped = raw.replace(/\$/g, '').trim();
  const decimalComma = stripped.match(/,(\d{2})$/);
  const normalized = decimalComma
    ? `${stripped.slice(0, -3).replace(/[,\s]/g, '')}.${decimalComma[1]}`
    : stripped.replace(/[,\s]/g, '');
  return parseFloat(normalized);
}

/**
 * True when `text` contains any dollar figure whose numeric value doesn't
 * match `allowedAmount` (within rounding tolerance). The one shared
 * detection path both branches of enforceDebtFigureInTopRecommendation use —
 * a figure equal to the allowed amount (e.g. the just-substituted
 * placeholder) is never flagged, regardless of how many times it appears.
 */
function containsUnauthorizedFigure(text: string, allowedAmount: number): boolean {
  const matches = text.match(DOLLAR_AMOUNT_RE) ?? [];
  return matches.some((m) => Math.abs(parseAmount(m) - allowedAmount) > 0.005);
}

function formatTargetDate(targetDate: string, locale: 'en' | 'fr'): string {
  return new Date(`${targetDate}-01T00:00:00`).toLocaleDateString(
    locale === 'fr' ? 'fr-CA' : 'en-CA',
    { month: 'long', year: 'numeric' }
  );
}

function buildFallbackDebtRecommendation(
  debtPayoff: DebtPayoffForRecommendation,
  locale: 'en' | 'fr'
): string {
  const amount = formatCurrency(debtPayoff.monthlyPayment);
  const targetMonth = formatTargetDate(debtPayoff.targetDate, locale);
  return locale === 'fr'
    ? `Ce mois-ci, priorisez ${debtPayoff.description} — le paiement prévu de ${amount}/mois reste la bonne cible pour un remboursement complet d'ici ${targetMonth}.`
    : `This month, prioritize ${debtPayoff.description} — the planned payment of ${amount}/month stays the right target to be fully paid off by ${targetMonth}.`;
}

/**
 * Generic fallback for when a template token leaks with NO debt payoff to
 * build a specific replacement from (confirmed live, 2026-07-28: a bare
 * credit-line draw, no debt account at all). Deliberately not debt-specific
 * — there's nothing real to say about a debt that doesn't exist.
 */
function buildGenericTokenFallback(locale: 'en' | 'fr'): string {
  return locale === 'fr'
    ? `Cette recommandation n'a pas pu être générée de façon fiable ce mois-ci — une nouvelle sera prête la prochaine fois que vous régénérerez.`
    : `This month's recommendation couldn't be generated safely — a fresh one will be ready the next time you regenerate.`;
}

/**
 * Enforces that topRecommendation can never ship an AI-invented dollar
 * figure for the debt's own required monthly payment, AND can never ship a
 * raw, unsubstituted {{...}} template token under any circumstance —
 * including when there's no debt payoff at all to substitute against
 * (confirmed live, 2026-07-28: the model applied the "write the placeholder"
 * style instruction even to a bare credit-line draw with no matching debt
 * account, and the old early return shipped the literal token untouched).
 */
export function enforceDebtFigureInTopRecommendation(
  text: string,
  debtPayoff: DebtPayoffForRecommendation | null,
  locale: 'en' | 'fr'
): string {
  if (!debtPayoff) {
    // No real figure exists to substitute a leaked token with — the only
    // safe move is to discard the whole recommendation, never to return a
    // literal template artifact to the user.
    return containsUnsubstitutedToken(text) ? buildGenericTokenFallback(locale) : text;
  }

  // Substitute the placeholder FIRST (if present) so the real figure is
  // already in place before scanning — the scan below then only ever flags
  // a figure that genuinely differs from the real amount, never the
  // substitution itself.
  const substituted = text.includes(DEBT_PAYMENT_PLACEHOLDER)
    ? text.split(DEBT_PAYMENT_PLACEHOLDER).join(formatCurrency(debtPayoff.monthlyPayment))
    : text;

  const mentionsDebt = substituted.toLowerCase().includes(debtPayoff.description.toLowerCase());
  if (mentionsDebt && containsUnauthorizedFigure(substituted, debtPayoff.monthlyPayment)) {
    // Either the model skipped the placeholder and typed its own digits, or
    // it used the placeholder correctly but padded the sentence with an
    // extra invented figure alongside it — never trust either shape.
    return buildFallbackDebtRecommendation(debtPayoff, locale);
  }

  // A DIFFERENT, unexpected template token could leak alongside a correctly
  // substituted DEBT_PAYMENT_PLACEHOLDER — same class of gap as the
  // placeholder-plus-extra-figure bug (2026-07-28), just for a stray token
  // instead of a stray dollar figure.
  if (containsUnsubstitutedToken(substituted)) {
    return buildFallbackDebtRecommendation(debtPayoff, locale);
  }

  return substituted;
}

// ---------------------------------------------------------------------------
// Fix 4 (2026-07-28): borrowed cash mislabeled as surplus, no debt card needed
// ---------------------------------------------------------------------------
//
// The existing aiContext disclosure ("Borrowed this month: $X...") is already
// unconditional on totalBorrowed > 0 — it does NOT depend on computedDebtPayoff
// existing (confirmed by reading regenerate-plan/route.ts's aiContext
// assembly). But that's still only a soft prompt instruction with no
// code-level check behind it — the same class of gap Fix 1/Fix 3 closed
// elsewhere. This adds an actual post-generation guard, called independently
// of enforceDebtFigureInTopRecommendation/computedDebtPayoff — it engages
// purely off totalBorrowed, whether or not a debt-payoff card exists at all.
//
// IMPORTANT — this is best-effort pattern matching over free prose, NOT a
// structural guarantee the way DEBT_PAYMENT_PLACEHOLDER substitution is.
// Substitution is genuinely impossible to get wrong (the AI never authors
// the digit, code inserts it). This guard instead infers intent from word
// proximity — it can miss a phrasing it wasn't taught, and (before the
// 2026-07-28 fix below) could false-positive on an unrelated word sharing a
// label's spelling near an unrelated coincidentally-equal dollar figure.
// Never describe this mechanism as making anything "impossible."
//
// PROXIMITY FIX (2026-07-28, Codex finding 4): confirmed false positive —
// "Your Extra category had a $1,000 refund; your credit-line draw was
// $1,000 and must be repaid." discarded the whole (valid) sentence, because
// the word "Extra" (part of an unrelated category's name) sat within the old
// 80-char-wide window around the FIRST $1,000 (an unrelated refund that
// merely happened to equal totalBorrowed too). Two independent bugs fixed
// together: (1) label words were matched by substring, not word boundary;
// (2) more fundamentally, "nearby" was too wide and didn't require the label
// to be grammatically attached to that specific figure. Measured empirically
// against real phrasings before picking the threshold: every genuine
// mislabeling case tested (e.g. "extra $1,000", "$1,000 of surplus") has its
// label within 1-4 characters of the figure; the false-positive repro's
// unrelated "Extra" sits 16 characters away. BORROWED_LABEL_PROXIMITY_CHARS
// is set well inside that gap, with margin on both sides.
const BORROWED_LABEL_PROXIMITY_CHARS = 10;

// English forms only here — French forms are added in coachingHelpers.ts's
// sibling list and Part C's extension of this file (kept adjacent, not
// scattered, per the standing rule below).
const SURPLUS_LABEL_WORDS_EN = ['surplus', 'extra', 'additional income', 'free cash', 'to invest', 'to save', 'available to', 'on top of'];

function buildBorrowedCashFallback(totalBorrowed: number, locale: 'en' | 'fr'): string {
  const amount = formatCurrency(totalBorrowed);
  return locale === 'fr'
    ? `Une partie de vos liquidités ce mois-ci (${amount}) provient d'un emprunt sur une marge de crédit, pas de revenus réels — gardez cela en tête avant de décider où diriger un montant supplémentaire ce mois-ci.`
    : `Part of this month's available cash (${amount}) was borrowed from a credit line, not earned — worth keeping that in mind before deciding where to direct anything extra this month.`;
}

/** Word-boundary match spans for every label in `labels`, across the whole text. */
function findLabelSpans(text: string, labels: string[]): { start: number; end: number }[] {
  const spans: { start: number; end: number }[] = [];
  for (const label of labels) {
    const re = new RegExp(`\\b${escapeRegExp(label)}\\b`, 'gi');
    for (const m of text.matchAll(re)) {
      if (m.index !== undefined) spans.push({ start: m.index, end: m.index + m[0].length });
    }
  }
  return spans;
}

/**
 * Enforces that topRecommendation never labels the household's real,
 * dated credit-line draw as surplus/extra/income. Runs purely off
 * `totalBorrowed` — never gated on computedDebtPayoff/a debt-payoff card
 * existing, so a draw with no matching debt account is still caught.
 * Returns `text` unchanged when there's nothing borrowed this month.
 *
 * Best-effort proximity heuristic (see the module-level note above) — a
 * figure must both (a) numerically equal totalBorrowed and (b) have a
 * whole-word label within BORROWED_LABEL_PROXIMITY_CHARS of it. Every
 * occurrence of the figure and every label are found independently
 * (matchAll on both) so a repeated figure — once honest, once mislabeled —
 * is judged occurrence-by-occurrence, never by the first match found.
 */
export function enforceBorrowedCashFraming(
  text: string,
  totalBorrowed: number,
  locale: 'en' | 'fr',
  labels: string[] = SURPLUS_LABEL_WORDS_EN
): string {
  if (totalBorrowed <= 0) return text;

  const labelSpans = findLabelSpans(text, labels);
  if (labelSpans.length === 0) return text;

  for (const match of text.matchAll(DOLLAR_AMOUNT_RE)) {
    if (Math.abs(parseAmount(match[0]) - totalBorrowed) > 0.005) continue;
    const figStart = match.index;
    if (figStart === undefined) continue;
    const figEnd = figStart + match[0].length;

    const nearbyLabel = labelSpans.some((span) => {
      const gapBefore = figStart - span.end; // label ends before the figure starts
      const gapAfter = span.start - figEnd;  // label starts after the figure ends
      return (gapBefore >= 0 && gapBefore <= BORROWED_LABEL_PROXIMITY_CHARS) ||
             (gapAfter >= 0 && gapAfter <= BORROWED_LABEL_PROXIMITY_CHARS);
    });

    if (nearbyLabel) return buildBorrowedCashFallback(totalBorrowed, locale);
  }
  return text;
}
