/**
 * Structural guard for plan.topRecommendation's debt-payoff dollar figure.
 *
 * Root cause (confirmed live, 2026-07-27): topRecommendation is generated by
 * planPrompt — an older AI call that predates the Coaching Layer and was
 * never wired into it. Its only protection was a soft instruction ("if you
 * reference debt payoff, use the exact numbers given"). Across two real
 * regenerate-plan runs for the same household/month/credit line (whose own
 * required payment is a fixed computedDebtPayoff.monthlyPayment), the model
 * stated two different dollar amounts for it. A stronger-worded instruction
 * is not a fix — the number must be code-owned, not AI-authored, the same
 * discipline goals/debtPayoff/coaching already use elsewhere in this route.
 *
 * Mechanism: planPrompt requires the model to write the literal placeholder
 * DEBT_PAYMENT_PLACEHOLDER wherever the debt's own monthly payment amount
 * would go, never digits. This alone doesn't structurally stop a model from
 * ignoring the instruction and typing its own number anyway — so
 * enforceDebtFigureInTopRecommendation is the actual gate: if the
 * placeholder is present, it's substituted with the real figure (the only
 * path that ever reaches the final output uses a code-owned number); if the
 * debt is named WITHOUT the placeholder AND a dollar amount appears anyway,
 * that means the model authored its own figure despite the instruction —
 * the entire recommendation is discarded and replaced with a deterministic,
 * code-built sentence using the real payment amount. Either path, the final
 * shipped figure can never be an AI-invented number.
 */

export const DEBT_PAYMENT_PLACEHOLDER = '{{DEBT_PAYMENT}}';

// Matches both English ($3,000 / $833.33) and French-Canadian (3000$ / 3 000,00 $)
// currency conventions — a fabricated figure must not slip past detection
// just because the model wrote it in French formatting.
const DOLLAR_AMOUNT_RE = /\$\s?[\d,]+(?:[.,]\d{1,2})?|[\d][\d,\s]*(?:[.,]\d{1,2})?\s?\$/;

export type DebtPayoffForRecommendation = {
  description: string;
  targetDate: string; // YYYY-MM
  monthlyPayment: number;
};

function formatCurrency(n: number): string {
  return `$${n.toFixed(2)}`;
}

function formatTargetDate(targetDate: string, locale: 'en' | 'fr'): string {
  return new Date(`${targetDate}-01T00:00:00`).toLocaleDateString(
    locale === 'fr' ? 'fr-CA' : 'en-CA',
    { month: 'long', year: 'numeric' }
  );
}

function buildFallbackDebtRecommendation(
  debtPayoff: DebtPayoffForRecommendation,
  locale: 'en' | 'fr'
): string {
  const amount = formatCurrency(debtPayoff.monthlyPayment);
  const targetMonth = formatTargetDate(debtPayoff.targetDate, locale);
  return locale === 'fr'
    ? `Ce mois-ci, priorisez ${debtPayoff.description} — le paiement prévu de ${amount}/mois reste la bonne cible pour un remboursement complet d'ici ${targetMonth}.`
    : `This month, prioritize ${debtPayoff.description} — the planned payment of ${amount}/month stays the right target to be fully paid off by ${targetMonth}.`;
}

/**
 * Enforces that topRecommendation can never ship an AI-invented dollar
 * figure for the debt's own required monthly payment. Returns `text`
 * unchanged when there's no debt payoff at all, or when the text doesn't
 * reference the debt by name (nothing to enforce).
 */
export function enforceDebtFigureInTopRecommendation(
  text: string,
  debtPayoff: DebtPayoffForRecommendation | null,
  locale: 'en' | 'fr'
): string {
  if (!debtPayoff) return text;

  if (text.includes(DEBT_PAYMENT_PLACEHOLDER)) {
    return text.split(DEBT_PAYMENT_PLACEHOLDER).join(formatCurrency(debtPayoff.monthlyPayment));
  }

  const mentionsDebt = text.toLowerCase().includes(debtPayoff.description.toLowerCase());
  if (mentionsDebt && DOLLAR_AMOUNT_RE.test(text)) {
    // The model named the debt and stated its own digits instead of the
    // required placeholder — never trust an unconstrained figure here.
    return buildFallbackDebtRecommendation(debtPayoff, locale);
  }

  return text;
}
