import type { LegalDocument } from './types';

/**
 * Founder-written copy, 2026-08-03.
 *
 * ⚠ The `billing`, `refunds` and `deletion` sections describe a paid tier,
 * automatic renewal, and in-app cancellation. NONE OF THAT IS IMPLEMENTED —
 * there is no Stripe integration in src/, and no subscription UI. Flagged to
 * the founder 2026-08-04; left as authored pending their decision. Do not treat
 * this comment as resolved until either billing ships or the copy changes.
 */
const termsEn: LegalDocument = {
  title: 'Terms of Service',
  lastUpdated: '2026-08-03',
  intro: [
    'Phare is operated by **Lineu Prompt Graeff**, a sole proprietor based in Quebec, Canada (“we”, “us”).',
    'By creating an account, you agree to these terms. They are written plainly on purpose. Questions: **support@phare.money**.',
  ],
  sections: [
    {
      id: 'what-phare-is',
      heading: 'What Phare is',
      body: [
        'Phare is a financial coaching tool for households. You enter your income, expenses, accounts, and goals, and Phare helps you see where your money is going, what is coming, and whether your plan is working. Part of it is generated by an AI service, which writes a monthly review and a plan in plain language.',
      ],
    },
    {
      id: 'not-financial-advice',
      heading: 'Phare is not financial advice',
      body: [
        '**This is the most important thing in this document.**',
        'We are not a financial advisor, financial planner, accountant, tax professional, mortgage broker, or lawyer, and Phare is not registered or licensed as any of these. Nothing Phare produces is financial, investment, tax, or legal advice.',
        'Phare’s plans, monthly reviews, recommendations, and projections are **informational tools based on the figures you enter**. They are generated in part by artificial intelligence, which can be wrong, can misread a situation, and can produce text that sounds confident while being unsuitable for your circumstances.',
        '**Every financial decision you make is yours alone, and you are solely responsible for it.** If you are making a decision that matters — a mortgage, an RRSP or TFSA contribution, a debt consolidation, anything with tax consequences — consult a qualified professional who knows your full situation. Phare does not know your full situation. It knows what you typed into it.',
        'Projections are estimates, not promises. A projected balance is what would happen if the assumptions hold. Assumptions do not always hold.',
      ],
    },
    {
      id: 'your-data-your-numbers',
      heading: 'Your data, your numbers',
      body: [
        'Phare works from what you enter. If a figure is wrong, missing, or miscategorized, the output will be wrong too — including the plan, the review, and every projection. We do not verify your entries against your bank, because Phare does not connect to your bank.',
        'Keeping your information accurate is your responsibility. Phare’s job is to be correct about the arithmetic on the numbers you give it.',
      ],
    },
    {
      id: 'accounts-and-households',
      heading: 'Accounts and households',
      body: [
        'You must be 18 or older and resident in Canada to create an account.',
        'Phare is organized around a **household**. A household holds up to **two people with logins**. You may also name other people — children, for example — so expenses can be attributed to them; they have no login and are not counted against the limit.',
        '**Everyone with a login in a household sees everything in it.** There is no private data inside a household. Invite someone only if you are comfortable with that.',
        'You are responsible for keeping your password secure and for everything done under your account. Tell us at **support@phare.money** if you believe someone else has access to it.',
      ],
    },
    {
      id: 'billing',
      heading: 'Pricing and payment',
      body: [
        'Phare offers a free tier and a paid tier, **Phare Pro**.',
        '**Phare Pro costs $15 CAD per month, or $150 CAD per year.** Prices are in Canadian dollars and applicable taxes are added at checkout. Payment is processed by Stripe; we do not store your card number.',
        'Subscriptions renew automatically — monthly plans each month, annual plans each year — at the price in effect at renewal. We will tell you in advance if a price changes, and you can cancel before it takes effect.',
        'Some households may be given promotional or complimentary access for a period. When that period ends, the account reverts to the free tier unless you subscribe. We will not charge you without your having entered payment details.',
      ],
    },
    {
      id: 'refunds',
      heading: 'Refunds',
      body: [
        '**You may request a full refund within 30 days of any charge**, whether monthly or annual, for any reason. Write to **support@phare.money** and we will refund it.',
        'After 30 days, a charge is not refundable, but you can cancel at any time. Cancelling stops the next renewal; you keep access for the rest of the period you have already paid for.',
      ],
    },
    {
      id: 'deletion',
      heading: 'Cancelling and deleting',
      body: [
        'You can cancel your subscription at any time from within the app. You keep Pro access until the end of the paid period, then move to the free tier.',
        'You can delete your account entirely from the Household page. Deletion is permanent and there is no grace period — we recommend exporting your data first, which the same page offers. What deletion removes and what it keeps is set out in our Privacy Policy, and differs depending on whether anyone else remains in your household.',
      ],
    },
    {
      id: 'availability',
      heading: 'Availability',
      body: [
        'We aim to keep Phare running and correct. We do not promise uninterrupted availability. Phare depends on services we do not control — hosting, database, email, and AI providers — and any of them can fail.',
        'We may change, add, or remove features. If we remove something you rely on, we will try to tell you first.',
      ],
    },
    {
      id: 'acceptable-use',
      heading: 'Acceptable use',
      body: [
        'Don’t use Phare to do anything illegal. Don’t try to break into other households’ data, overload the service, scrape it, or reverse-engineer it. Don’t resell access. Don’t upload someone else’s financial information without their knowledge.',
        'We may suspend or close an account that does these things.',
      ],
    },
    {
      id: 'your-data',
      heading: 'Your content',
      body: [
        'Your financial data is yours. We do not claim ownership of it. We use it to operate Phare for you — including sending a summary of it to our AI provider to generate your plan and review, as described in the Privacy Policy — and for nothing else.',
        'The software, design, and text of Phare are ours.',
      ],
    },
    {
      id: 'liability',
      heading: 'Limitation of liability',
      body: [
        'To the extent the law allows: Phare is provided as-is, without warranty of any kind. We are not liable for financial losses, missed payments, penalties, tax consequences, lost opportunities, or any other damages arising from your use of Phare or from decisions you made with it.',
        'Our total liability to you for any claim is limited to the amount you paid us in the twelve months before the claim arose.',
        'Nothing here limits rights you have under Quebec consumer protection law that cannot be waived.',
      ],
    },
    {
      id: 'termination',
      heading: 'Ending this agreement',
      body: [
        'You can stop using Phare and delete your account at any time.',
        'We can close your account if you breach these terms, or if we discontinue the service. If we discontinue Phare, we will give you reasonable notice and time to export your data, and refund any unused portion of a subscription you have paid for.',
      ],
    },
    {
      id: 'changes',
      heading: 'Changes to these terms',
      body: [
        'If we change these terms in a way that matters, we will ask you to review and accept them the next time you sign in. Continuing to use Phare after that means you accept the new terms. If you do not accept them, you can delete your account and request a refund of any unused paid period.',
      ],
    },
    {
      id: 'governing-law',
      heading: 'Governing law',
      body: [
        'These terms are governed by the laws of Quebec and the laws of Canada that apply there. Any dispute will be heard in the courts of the judicial district of Montreal, Quebec.',
      ],
    },
    {
      id: 'contact',
      heading: 'Contact',
      body: [
        '**support@phare.money**',
        'Lineu Prompt Graeff, sole proprietor — Quebec, Canada',
      ],
    },
  ],
};

export default termsEn;
