-- =============================================================================
-- DEPRECATED — superseded by scripts/reset-household.sql.
--
-- This file and scripts/reset-household.sql both claimed to be "the
-- pre-trial reset script" for a while (flagged, unresolved, in an earlier
-- session) — they've now been consolidated into one canonical script:
-- scripts/reset-household.sql. Use that one instead. It carries forward
-- this file's inline-UUID DO-block style (no temp table) and existence
-- guard, adds queryable verification result sets (this file only had
-- RAISE NOTICE, which isn't a result set you can screenshot or diff), and
-- includes tables added after this file was written (recurring_skipped_dates,
-- card_envelope_items, account_balance_anchors).
--
-- This file is kept only so old links/notes that reference it by name still
-- resolve to an explanation instead of a 404. Do not run it — the queries
-- below are commented out.
-- =============================================================================

-- (original body intentionally removed — see scripts/reset-household.sql)
