-- =============================================================================
-- Phare — account integrity
-- Applied 2026-06-18.
-- Ensures transactions.account_id and recurring_items.account_id are never NULL.
-- =============================================================================

-- 1. Heal any existing NULL rows by assigning them to the household's chequing account.
UPDATE transactions t
SET account_id = (
  SELECT a.id FROM accounts a
  WHERE a.household_id = t.household_id AND a.type = 'chequing'
  LIMIT 1
)
WHERE t.account_id IS NULL;

UPDATE recurring_items r
SET account_id = (
  SELECT a.id FROM accounts a
  WHERE a.household_id = r.household_id AND a.type = 'chequing'
  LIMIT 1
)
WHERE r.account_id IS NULL;

-- 2. Change transactions.account_id: ON DELETE SET NULL → ON DELETE RESTRICT + NOT NULL.
--    The column's FK name is auto-generated by Postgres as transactions_account_id_fkey.
ALTER TABLE transactions
  DROP CONSTRAINT IF EXISTS transactions_account_id_fkey;
ALTER TABLE transactions
  ADD CONSTRAINT transactions_account_id_fkey
    FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE RESTRICT;
ALTER TABLE transactions
  ALTER COLUMN account_id SET NOT NULL;

-- 3. Change recurring_items.account_id: same treatment.
ALTER TABLE recurring_items
  DROP CONSTRAINT IF EXISTS recurring_items_account_id_fkey;
ALTER TABLE recurring_items
  ADD CONSTRAINT recurring_items_account_id_fkey
    FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE RESTRICT;
ALTER TABLE recurring_items
  ALTER COLUMN account_id SET NOT NULL;

-- bridge_source_account remains nullable (not all transactions are bridge rows).
