-- =============================================================================
-- Phare — who wrote this review, and one review per month. 2026-08-10.
--
-- PENDING APPLICATION — do not apply to production without founder sign-off.
--
-- Two changes, both in service of the one-review-per-month archive model.
--
-- WHY `generated_by` EXISTS. Under one-per-month, a manual regeneration and the
-- scheduled letter compete for the same (household_id, review_month) slot. If
-- they are indistinguishable, whoever writes first wins forever: a family who
-- presses Regenerate on 14 August occupies '2026-08', and on 1 September the
-- cron's insert raises 23505, reports `claimed_by_other` — which reads exactly
-- like healthy idempotency — and that household's August review is permanently
-- the half-month draft they generated by hand. This column is what lets the
-- cron tell "already done" from "done provisionally, by the family, mid-month"
-- and replace only the latter.
--
-- WHY THE UNIQUE INDEX BECOMES TOTAL. It is partial (WHERE review_month IS NOT
-- NULL), and PostgREST's upsert emits `ON CONFLICT (household_id, review_month)`
-- with no predicate. Postgres cannot infer a PARTIAL index from that, so the
-- upsert fails outright with "no unique or exclusion constraint matching the ON
-- CONFLICT specification". Dropping the WHERE makes it inferrable.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- 1. WHO GENERATED THIS REVIEW.
--
--   'cron'   — the scheduled monthly letter. Canonical.
--   'manual' — POST /api/regenerate-plan. Real, and the family may have paid a
--              refresh for it, but PROVISIONAL: the cron may replace it with the
--              end-of-month letter for the same month.
--   NULL     — neither. Onboarding letters are not reviews of a month and never
--              take part in the slot; they keep NULL forever.
-- -----------------------------------------------------------------------------
ALTER TABLE conversations
  ADD COLUMN IF NOT EXISTS generated_by text;

ALTER TABLE conversations
  DROP CONSTRAINT IF EXISTS conversations_generated_by_valid;
ALTER TABLE conversations
  ADD CONSTRAINT conversations_generated_by_valid
  CHECK (generated_by IS NULL OR generated_by IN ('cron', 'manual'));


-- -----------------------------------------------------------------------------
-- 2. BACKFILL — derivable with certainty, so it is not guesswork.
--
-- Only the cron has ever written a non-null review_month (regenerate-plan
-- deliberately left it NULL, save-plan never set it). So every monthed row is
-- 'cron' by construction, and every unmonthed monthly_review row is a manual
-- refresh. Onboarding rows are left NULL, which is their permanent value.
--
-- Written as `WHERE generated_by IS NULL` so re-running is a no-op and cannot
-- relabel a row that later code has already classified.
-- -----------------------------------------------------------------------------
UPDATE conversations
   SET generated_by = 'cron'
 WHERE generated_by IS NULL
   AND review_month IS NOT NULL;

UPDATE conversations
   SET generated_by = 'manual'
 WHERE generated_by IS NULL
   AND review_month IS NULL
   AND type = 'monthly_review';


-- -----------------------------------------------------------------------------
-- 3. THE UNIQUE INDEX BECOMES TOTAL.
--
-- SAFE DESPITE THE DUPLICATE NULLS, and this is the part that looks alarming.
-- A household can have many rows with review_month NULL (every onboarding
-- letter, every pre-cutover manual refresh). Those do NOT collide: Postgres
-- treats NULLs as DISTINCT in a unique index by default, so (hh, NULL) may
-- repeat without limit. The default is NULLS DISTINCT — this migration must
-- NOT be "improved" later by adding NULLS NOT DISTINCT (PG15+), which would
-- reject every household that has more than one onboarding letter.
--
-- The guarantee for non-null months is therefore byte-for-byte what the partial
-- index already gave. Only the inferrability by ON CONFLICT changes.
-- -----------------------------------------------------------------------------
DROP INDEX IF EXISTS idx_conversations_review_month_claim;

CREATE UNIQUE INDEX IF NOT EXISTS idx_conversations_review_month_claim
  ON conversations (household_id, review_month);


-- =============================================================================
-- VERIFY — run after applying. Expect every row PASS.
-- =============================================================================
--
-- WITH checks AS (
--   SELECT 'generated_by column exists (text, nullable)' AS check_name,
--          CASE WHEN EXISTS (SELECT 1 FROM information_schema.columns
--                WHERE table_schema='public' AND table_name='conversations'
--                  AND column_name='generated_by'
--                  AND data_type='text' AND is_nullable='YES')
--               THEN 'PASS' ELSE 'FAIL' END AS status
--   UNION ALL
--   SELECT 'CHECK constraint restricts to cron/manual/NULL',
--          CASE WHEN EXISTS (SELECT 1 FROM pg_constraint
--                WHERE conname='conversations_generated_by_valid')
--               THEN 'PASS' ELSE 'FAIL' END
--   UNION ALL
--   SELECT 'every monthed review is labelled cron',
--          CASE WHEN NOT EXISTS (SELECT 1 FROM conversations
--                WHERE review_month IS NOT NULL AND generated_by IS DISTINCT FROM 'cron')
--               THEN 'PASS' ELSE 'FAIL — a monthed row was written by something else' END
--   UNION ALL
--   SELECT 'every onboarding letter stays NULL',
--          CASE WHEN NOT EXISTS (SELECT 1 FROM conversations
--                WHERE type='onboarding' AND generated_by IS NOT NULL)
--               THEN 'PASS' ELSE 'FAIL — an onboarding row was labelled' END
--   UNION ALL
--   SELECT 'unique index is TOTAL (no WHERE predicate)',
--          CASE WHEN EXISTS (SELECT 1 FROM pg_indexes
--                WHERE schemaname='public'
--                  AND indexname='idx_conversations_review_month_claim'
--                  AND indexdef ILIKE '%UNIQUE%'
--                  AND indexdef NOT ILIKE '%WHERE%')
--               THEN 'PASS' ELSE 'FAIL — still partial, ON CONFLICT cannot infer it' END
--   UNION ALL
--   SELECT 'one review per (household, month) still holds',
--          CASE WHEN NOT EXISTS (
--                SELECT 1 FROM conversations WHERE review_month IS NOT NULL
--                 GROUP BY household_id, review_month HAVING count(*) > 1)
--               THEN 'PASS' ELSE 'FAIL' END
-- )
-- SELECT * FROM checks ORDER BY status, check_name;
--
-- -- What the backfill decided, by kind (expect no surprising combinations):
-- SELECT type, (review_month IS NOT NULL) AS has_month, generated_by, count(*)
--   FROM conversations
--  GROUP BY 1, 2, 3
--  ORDER BY 1, 2, 3;
--
-- -- Prove the index behaves, WITHOUT substituting an id anywhere (rolls back).
-- -- The third check is the important one: the VERIFY above proves the index is
-- -- total, which is only the PRECONDITION for ON CONFLICT inference. Whether
-- -- PostgREST's upsert actually resolves against it is a separate fact, and it
-- -- is the one that decides whether Regenerate works in production.
-- --
-- --   BEGIN;
-- --   DO $$
-- --   DECLARE hh uuid; n int; txt text;
-- --   BEGIN
-- --     SELECT household_id INTO hh FROM conversations LIMIT 1;
-- --
-- --     -- 1. duplicate NULLs must STILL insert (NULLS DISTINCT)
-- --     INSERT INTO conversations (household_id, user_id, type, messages, review_month)
-- --     VALUES (hh, NULL, 'onboarding', '[]'::jsonb, NULL),
-- --            (hh, NULL, 'onboarding', '[]'::jsonb, NULL);
-- --     RAISE NOTICE 'duplicate NULLs allowed: PASS';
-- --
-- --     -- 2. a duplicate MONTH must still be rejected
-- --     BEGIN
-- --       INSERT INTO conversations (household_id, user_id, type, messages, review_month)
-- --       VALUES (hh, NULL, 'monthly_review', '[]'::jsonb, '2099-01'),
-- --              (hh, NULL, 'monthly_review', '[]'::jsonb, '2099-01');
-- --       RAISE NOTICE 'duplicate month rejected: FAIL';
-- --     EXCEPTION WHEN unique_violation THEN
-- --       RAISE NOTICE 'duplicate month rejected: PASS';
-- --     END;
-- --
-- --     -- 3. ON CONFLICT must infer the index and REPLACE
-- --     INSERT INTO conversations (household_id, user_id, type, messages, review_month, generated_by)
-- --     VALUES (hh, NULL, 'monthly_review', '["first"]'::jsonb, '2099-02', 'manual')
-- --     ON CONFLICT (household_id, review_month) DO UPDATE SET messages = EXCLUDED.messages;
-- --     INSERT INTO conversations (household_id, user_id, type, messages, review_month, generated_by)
-- --     VALUES (hh, NULL, 'monthly_review', '["second"]'::jsonb, '2099-02', 'manual')
-- --     ON CONFLICT (household_id, review_month) DO UPDATE SET messages = EXCLUDED.messages;
-- --     SELECT count(*), max(messages::text) INTO n, txt
-- --       FROM conversations WHERE household_id = hh AND review_month = '2099-02';
-- --     RAISE NOTICE 'upsert infers the index: % (rows=%, messages=%)',
-- --       CASE WHEN n = 1 AND txt LIKE '%%second%%' THEN 'PASS' ELSE 'FAIL' END, n, txt;
-- --   END $$;
-- --   ROLLBACK;
-- =============================================================================
